### ISSUE TITLE
Validation duplicates, go loop var override in validator

### ISSUE THREAD

**Issue by fe3dback** [fe3dback/go-arch-lint#14]
archfile:

```yaml
deps:
  main-cli:
    mayDependOn:
      - version
      - app-cli2
```

## Problem 1

- `version` - exist
- `app-cli2` - not exist in components

```
[Archfile] path '$.deps.main-cli.mayDependOn[0]': unknown component 'app-cli2':
  114 |   main-cli:
  115 |     mayDependOn:
> 116 |       - version
                ^
  117 |       - app-cli2
  118 |
[Archfile] path '$.deps.main-cli.mayDependOn[1]': unknown component 'app-cli2':
  114 |   main-cli:
  115 |     mayDependOn:
  116 |       - version
> 117 |       - app-cli2
                ^
  120 |   app-http:
```

## Problem 2

go for loop override component name, so only last element in `mayDependOn` and `canUse` is checked by validator.

```yaml
deps:
  main-cli:
    mayDependOn:
      - invalid_component_zzz # <- this will not checked
      - app-cli
```
