### ISSUE TITLE
Deps re-usage with yaml anchor idea

### ISSUE THREAD

**Issue by fe3dback** [fe3dback/go-arch-lint#18]
File may contain definitions section, for yaml anchors.
- go-arch spec will not use this section.
- yaml loader will preload yaml anchors
- plugin should parse "definitions" as "deps" for code completion, etc..

example:
```
definitions:
  operation-consumer: &operation-consumer
    canUse:
      - sqlx
      - kafka
   mayDependOn:
     - repository

deps;
  operation-upsert-books: *operation-consumer
  operation-upsert-authors: *operation-consumer
```
