### ISSUE TITLE
random slice read and priority

### ISSUE THREAD

**Issue by fe3dback** [fe3dback/go-arch-lint#20]
Config example:
```
components:
  services_http:
    in: internal/services/*
  services_kafka:
    in: internal/services/kafka/*
```

This will by read randomly, in different order, so each run, one or another component will have more priority for same file, and lint result will by random between OK and WARN.
