### ISSUE TITLE
path priority

### ISSUE THREAD

**Issue by fe3dback** [fe3dback/go-arch-lint#21]
One or more components can declare (cover) same files, see #20 for example

Each "in" path should by prioritized some way, and component with highter priority should hold file.

Good start is see how this problem solved in URI libs, like VUE router, etc..

```
components:
  services_http:
    in: internal/services/* <- can cover kafka too
  services_kafka:
    in: internal/services/kafka/*
```

also some explain command will by useful for debug with map between components and modules:

```
Component       Module
commands        
		/commands/check
                /commands/version
                /commands/root
services	
		/services/a
		/services/b
		/services/c
                               
```
