### ISSUE TITLE
I need help to configure the linter

### ISSUE THREAD

**Issue by LazarenkoA** [fe3dback/go-arch-lint#38]
`.go-arch-lint.yml` located at the root of the project, the content:
```yaml

version: 1

excludeFiles:
  - "^.*_test\\.go$"
  - "^.*\/test\/.*$"

exclude:
  - tests

components:
  main:
    in: cmd/**  # wildcard many levels
  framework:
    in:
      - db # wildcard one level
      - web
  adapters:
    in:
      - controllers/*
      - gateway
  entity:
    in: entity/*
  utils:
    in: utils
  pkg:
    in: pkg

commonComponents:
  - utils

deps:
  main:
    anyProjectDeps: true
    anyVendorDeps: true
  framework:
    mayDependOn:
      - adapters
  adapters:
    mayDependOn:
      - entity
```

I want to make sure that the dependence is checked for such compliance, the `framework` may depend on the adapters layer, and adapters on the entity.
`framework->adapters->entity`

I tried to perform a check on the config that I specified above, I run the command
`docker run --rm fe3dback/go-arch-lint:latest-stable-release check --project-path /Users/user1/Documents/GIT/project` 
get an error
`failed to assemble input params: failed to assemble project info: not found archfile in '/Users/user1/Documents/GIT/project/.go-arch-lint.yml'` 
if execute `cat /Users/user1/Documents/GIT/project/.go-arch-lint.yml` the contents of the config will be displayed in the console

Additional question
what is the difference between `canDependOn`, `canUse`, `mayDependOn` (I didn't find a description in the documentation)? `canDependOn` is given as an example in the readme,`mayDependOn` used in https://github.com/fe3dback/go-arch-lint/blob/master/.go-arch-lint.yml
`canUse` only for vendor models?

**Comment by fe3dback** [comment]
Hello, you run binary in docker container, this config file exist in your host system, but not in container.

You need to mount project as docker volume, inside container, and run it like this:
```
cd /Users/user1/Documents/GIT/project
docker run --rm -v ${PWD}:/app fe3dback/go-arch-lint:latest-stable-release check --project-path /app
```

**Comment by fe3dback** [comment]
Also for using some features, like multiple "in" section  in config, version should be at least 2+

**Comment by LazarenkoA** [comment]
everything worked out with the launch, thank you. There are still configuration questions, if I add
```yaml
vendors:
  sharedpkg:
    in: stash/scpl/sharedpkg/**

commonVendors:
  - sharedpkg
```

get an the error
Component framework file /web/http.go shouldn't depend on stash/scpl/sharedpkg/logger/v2

however, this path worked `stash.sigma.sbrf.ru/scpl/sharedpkg/*/**`, I don't know if it's a bug or a feature.

Another question:
here is such a structure
<img width="247" alt="image" src="https://user-images.githubusercontent.com/15386101/186874595-676df7eb-d359-4ed5-8ce1-032816ac9952.png">

here is such a configuration for it
```yaml
  entity:
    in: entity/**
```
that is, all this is an entity, how to make sure that dependencies are not checked between each other inside the entity?

**Comment by LazarenkoA** [comment]
excellent

**Comment by LazarenkoA** [comment]
closed the issues prematurely, why does this error occur?
```

Dependency framework -\-> adapters not allowed
  ├─ framework db.Ignite in /db/ignite.go:12
  └─ adapters New in /controllers/adapters/adapter.go:10
 
     /app/web/http.go:26
     >   26 |   dbadapter := adapter.New(srv, dbIgnite, conf.Ignite)

```

according to the rules, framework -> adapters dependence is allowed

```yaml
  framework:
    mayDependOn:
      - adapters
      - framework
```

**Comment by fe3dback** [comment]
This is new feature in v3 config called `deepscan`

```
version: 3
allow:
  deepScan: true
```

When is on, linter will check not only imports, but all code itself, and all interface dependencies.

What exactly happens on code:

1) You have struct `db.Ignite in /db/ignite.go:12` that belongs to `framework` component
2) You have function `New` in `/controllers/adapters/adapter.go:10` that belongs to `adapters` component

So, here:
```
dbadapter := adapter.New(srv, dbIgnite, conf.Ignite)
```

you pass db.Ignite `framework` as dependency to `adapter`, and in term of rules:
- `adapter` has not directly dependency on `framework`
- that is not allowed in rules.

This must be allowed in config like this:
```
  adapters:
    mayDependOn:
      - framework
```

or, just turnoff deep scan checking

**Comment by LazarenkoA** [comment]
now it's clear, thanks for the detailed answer

**Comment by LazarenkoA** [comment]
I'm sorry, but I'll reopen issue again. 
in `/db/ignite.go:12` i have structure, in `/controllers/adapters/adapter.go:10` i have function `New` but without depend, here is the signature `New(string, DB, *Config)` where DB is interface which is described in the adapters layer.

**Comment by LazarenkoA** [comment]
I realized, need explicit conversion to interface on framework layer  for example `dbadapter := adapter.New(srv, adapter.DB(dbIgnite), conf.Ignite)`, I tried, there  no errors, but is this correct? it seems there was no dependency without explicit conversion?

**Comment by fe3dback** [comment]
> but is this correct

no, its not. This just method to trick the linter )

Anyway code has undirect dependency `framework` -> `adapter`.
If you want dependencies like this, just add it to config:

```
  adapters:
    mayDependOn:
      - framework
```

If you not like this, linter will give three another options:
- turn off deepscan feature globally for entire project

```
version: 3
allow:
  deepScan: false
```

- turn off deepscan feature localy only for this component, for example "adapters"

```
deps
  adapters:
    deepScan: false
```

- refactor code, that break specified rules

**Comment by LazarenkoA** [comment]
> Anyway code has undirect dependency framework -> adapter.
the framework -> adapter dependency is correct here, but it is described in my rules, why does the linker swear? I don't see the inverse dependence

**Comment by LazarenkoA** [comment]
in addition, the error text "Dependency framework -\-> adapters not allowed" but not adapters -> framework. but dependency `framework -> adapters` is allowed in the rules

**Comment by fe3dback** [comment]
If config from first message is actual, its contain only one allow rule:
```yaml
  framework:
    mayDependOn:
      - adapters
```

this rule allow `adapter --> framework` injection
but in code is `framework --> adapters` injection

so, you need to add this to rules:

```yaml
  framework: // (allow adapter --> framework)
    mayDependOn:
      - adapters

  adapters: // (allow framework --> adapter)
    mayDependOn:
      - framework
```

**Comment by LazarenkoA** [comment]
Now I'm completely confused (
I think this rule
```yaml
 framework:
    mayDependOn:
      - adapters
```
allow to contain links from framework layer to objects of adapter layer?
my example
```
/app/web/http.go:26
     >   26 |   dbadapter := adapter.New(srv, dbIgnite, conf.Ignite)
```
`/app/web/http.go:26` - framework layer
`adapter.New` -  adapter layer

since the framework layer links to the adapter layer (that's what I wanted, that's my idea), I don't want to prescribe in the rules that the adapter layer depends on the framework (this contradicts the clean architecture). But what I can't understand is why linter thinks that there is an adapter dependency on the framework if they are linked through an interface.
By the way, dbadapter := adapter.New(srv, db Migrate, **conf.Ignore**) conf.Ignite is also in the adapter layer, and is also created in the framework layer, but the linter does not errors at it.
