### ISSUE TITLE
glob matching failed if both `*` and `**` exists in the pattern

### ISSUE THREAD

**Issue by wzy9607** [fe3dback/go-arch-lint#47]
```yaml
version: 3
workdir: .

components:
  main:
    in:
      - main
  infrastructure:
    in:
      - pkg/*/infrastructure/**

deps:
  main:
    mayDependOn:
      - infrastructure
```

go-arch-lint 1.11.0 reports that `not found directories for 'pkg/*/infrastructure/**'` despite file `pkg/abc/infrastructure/repository/a.go` exist.

Both `pkg/abc/infrastructure/**` and `pkg/*/infrastructure/*` works.
