### ISSUE TITLE
Forbid component for all code

### ISSUE THREAD

**Issue by SealOfTime** [fe3dback/go-arch-lint#51]
Quite often I've come to see "bad" dependencies being used in code to solve problems. that are already solved via different dependencies in the majority of codebase.
It would really help to have a way to forbid usage of such dependencies (even better to suggest alternatives)

As an example:
1. Project uses github.com/stretchr/testify's `assert` and `require` packages
2. But new contributor adds dependency on github.com/gotestyourself/gotest.tools's similarly named packages

I propose we add option to ban dependency for all code, like this:
```yaml
vendors:
    testify:
        in: github.com/stretchr/testify/**
    gotest.tools:
         in: github.com/gotestyourself/gotest.tools/**

forbiddenVendors:
    gotest.tools
```

Additionally, I propose we add a way to configure a message explaining how this restriction must be mitigated:
```yaml
forbiddenVendors:
    gotest.tools:
         message: Instead use github.com/stretchr/testify
```
