### ISSUE TITLE
_test package make package re-import it self

### ISSUE THREAD

**Issue by johnfercher** [fe3dback/go-arch-lint#59]
I'm creating an example of a [hexagonal architecture](https://github.com/johnfercher/go-hexagonal) to my team and I found something that maybe we could change the behavior.

In go we have the pattern to separate the productive package and the [test packakge](https://pkg.go.dev/cmd/go@master#hdr-Test_packages), by changing manually the package name in test files adding a `_test` suffix (how you can se [here](https://github.com/johnfercher/go-hexagonal/blob/main/internal/kycservices/userregister_test.go)). This help us to avoid `cyclic dependencies`.

This pattern made me have to define a self dependency from the package which have tests using this pattern: https://github.com/johnfercher/go-hexagonal/blob/4f1803a8e09824ffdfe6673f14161d13d9c04d17/.go-arch-lint.yml#L50-L57

```yml
  implementations:
    mayDependOn:
      - ports
      - drivers
      - drivens
      - implementations
    canUse:
      - assert
```

**implementations.mayDependOn.implementations**

Would be possible to ignore these `_test` suffixes?
