### ISSUE TITLE
Add ability to report issues starting from the specific revision

### ISSUE THREAD

**Issue by ilya-hontarau** [fe3dback/go-arch-lint#60]
It will be great to have the same feature golangci-lint has, that gives ability to report the code starting from the specific git ref:
```
  new-from-rev: HEAD
  # Show only new issues created in git patch with set file path.
  # Default: ""
```

**Comment by fe3dback** [comment]
What's the purpose of such a thing, what's the use case? (how can it be useful?)

The only option that comes to my mind is the simpler option of adding a linter to an existing project. But this can be done by adding bad dependencies to the config (allowing them explicitly), and marking them with a comment for later fixing (ideally with a task number in jira, for example).

Example:
```yaml
components:
  handler: ..
  service: ..
  repository: ..

deps:
  handler:
    mayDependOn:
      - service
      - repository # todo WTF (fix-me in PRJ-3941)

  service:
    mayDependOn:
      - repository
```
